import { Link } from 'react-router-dom';
import Navbar from '../components/Navbar';
import {
  BookOpen,
  Brain,
  Target,
  CalendarCheck,
  BarChart3,
  Clock,
  ArrowRight,
  CheckCircle2,
} from 'lucide-react';

const features = [
  {
    icon: Brain,
    title: 'AI-Powered Schedules',
    description: 'Get personalized study plans generated by AI based on your goals, availability, and learning pace.',
  },
  {
    icon: Target,
    title: 'Goal-Oriented Planning',
    description: 'Set clear objectives — exams, certifications, or skill mastery — and track your path to success.',
  },
  {
    icon: CalendarCheck,
    title: 'Daily Task Management',
    description: 'Break down your study plan into actionable daily tasks with built-in progress tracking.',
  },
  {
    icon: BarChart3,
    title: 'Analytics & Insights',
    description: 'Visualize your study habits, completion rates, and streaks to stay motivated and on track.',
  },
  {
    icon: Clock,
    title: 'Smart Break Scheduling',
    description: 'Choose from Pomodoro, extended, or deep work sessions to match your preferred study rhythm.',
  },
  {
    icon: BookOpen,
    title: 'Multi-Subject Support',
    description: 'Manage multiple study plans simultaneously — from coding to science to languages.',
  },
];

const steps = [
  { number: '01', title: 'Set Your Goal', description: 'Tell us what you want to learn and by when.' },
  { number: '02', title: 'Customize Preferences', description: 'Choose your study hours, break style, and focus areas.' },
  { number: '03', title: 'Get Your Plan', description: 'Receive a personalized, day-by-day study schedule.' },
  { number: '04', title: 'Track & Improve', description: 'Complete tasks, monitor progress, and adapt as you go.' },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-white">
      <Navbar />

      {/* ===== HERO ===== */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-[#EEF3FB] via-white to-[#F3F6FC]" />
        <div className="absolute top-0 right-0 w-96 h-96 bg-[#DCE6F7]/30 rounded-full blur-3xl -translate-y-1/2 translate-x-1/3" />
        <div className="absolute bottom-0 left-0 w-72 h-72 bg-[#E3EAF7]/30 rounded-full blur-3xl translate-y-1/2 -translate-x-1/3" />

        <div className="relative max-w-7xl mx-auto px-4 pt-20 pb-24 lg:pt-32 lg:pb-36">
          <div className="text-center max-w-3xl mx-auto">

            <span className="inline-flex items-center gap-2 px-4 py-1.5 bg-[#EEF3FB] text-[#4A6FA5] text-sm font-medium rounded-full mb-6">
              <CheckCircle2 className="w-4 h-4" />
              AI-Powered Study Planning
            </span>

            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-gray-900 leading-tight">
              Study Smarter,{' '}
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#4A6FA5] to-[#7A96C2]">
                Not Harder
              </span>
            </h1>

            <p className="mt-6 text-lg sm:text-xl text-gray-600 leading-relaxed">
              Create personalized study schedules that adapt to your goals, time availability, and
              learning pace. Stop procrastinating, start achieving.
            </p>

            <div className="mt-10 flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                to="/signup"
                className="inline-flex items-center gap-2 px-8 py-3.5 bg-[#4A6FA5] text-white font-semibold rounded-xl hover:bg-[#3F5F92] transition shadow-lg shadow-[#DCE6F7]"
              >
                Get Started Free
                <ArrowRight className="w-5 h-5" />
              </Link>

              <Link
                to="/login"
                className="inline-flex items-center gap-2 px-8 py-3.5 bg-white text-gray-700 font-semibold rounded-xl border border-gray-300 hover:bg-gray-50 transition"
              >
                Login
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* ===== FEATURES ===== */}
      <section className="py-20 bg-gray-50" id="features">
        <div className="max-w-7xl mx-auto px-4">

          <div className="text-center mb-16">
            <h2 className="text-3xl sm:text-4xl font-bold text-gray-900">
              Everything You Need to{' '}
              <span className="text-[#4A6FA5]">Ace Your Studies</span>
            </h2>

            <p className="mt-4 text-lg text-gray-500 max-w-2xl mx-auto">
              Powerful tools designed to help you plan, focus, and track your learning journey.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature) => (
              <div
                key={feature.title}
                className="bg-white rounded-xl p-6 border border-gray-200 hover:shadow-lg hover:-translate-y-1 transition-all"
              >
                <div className="w-12 h-12 bg-[#EEF3FB] rounded-xl flex items-center justify-center mb-4">
                  <feature.icon className="w-6 h-6 text-[#4A6FA5]" />
                </div>

                <h3 className="text-lg font-semibold text-gray-900 mb-2">{feature.title}</h3>

                <p className="text-sm text-gray-500">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ===== HOW IT WORKS ===== */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 text-center">

          <h2 className="text-3xl sm:text-4xl font-bold text-gray-900">
            How It <span className="text-[#4A6FA5]">Works</span>
          </h2>

          <p className="mt-4 text-lg text-gray-500">
            Four simple steps to your personalized study plan.
          </p>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-8 mt-12">
            {steps.map((step) => (
              <div key={step.number}>
                <span className="text-5xl font-extrabold text-[#EEF3FB]">{step.number}</span>

                <h3 className="text-lg font-semibold text-gray-900 mt-2">
                  {step.title}
                </h3>

                <p className="text-sm text-gray-500">{step.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ===== CTA ===== */}
      <section className="py-20 bg-gradient-to-r from-[#4A6FA5] to-[#7A96C2] text-center">

        <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
          Ready to Transform Your Study Habits?
        </h2>

        <p className="text-lg text-white/90 mb-8">
          Join thousands of students who are studying smarter with AI-powered planning.
        </p>

        <Link
          to="/signup"
          className="inline-flex items-center gap-2 px-8 py-3.5 bg-white text-[#4A6FA5] font-semibold rounded-xl hover:bg-gray-50 transition shadow-lg"
        >
          Start Planning Now
          <ArrowRight className="w-5 h-5" />
        </Link>
      </section>

      {/* ===== FOOTER ===== */}
      <footer className="bg-gray-900 py-12">
        <div className="max-w-7xl mx-auto px-4 text-center text-gray-400">

          <div className="flex items-center justify-center gap-2 mb-4">
            <BookOpen className="w-6 h-6 text-[#7A96C2]" />
            <span className="text-lg font-bold text-white">
              Edu<span className="text-[#7A96C2]">AI</span>
            </span>
          </div>

          <p>&copy; {new Date().getFullYear()} EduAI. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
